import "./globals.css";
import Navbar from "@/components/navbar-section/Navbar";
import AuthProvider from "@/lib/AuthProvider";
import { GlobalContextProvider } from "@/context/store";
import LoadingEquipment from "@/components/basic-items/LoadingEquipment";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <GlobalContextProvider>
          <body className={`XXdark-theme`}>
            <Navbar />
            <div>{children}</div>
            <LoadingEquipment />
            <div id="hidden-items---"></div>
          </body>
        </GlobalContextProvider>
      </AuthProvider>
    </html>
  );
}
